---
- include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_os_family != "Debian"

- name: Ensure CouchPotato service group exists
  group:
    name: "{{ couchpotato_group_name }}"
    system: true
    state: present

- name: Ensure CouchPotato service user exists
  user:
    name: "{{ couchpotato_user_name }}"
    group: "{{ couchpotato_group_name }}"
    home: "{{ couchpotato_user_home }}"
    system: true
    state: present

- name: Ensure CouchPotato home directory exists
  file:
    dest: "{{ couchpotato_user_home }}"
    owner: "{{ couchpotato_user_name }}"
    group: "{{ couchpotato_group_name }}"
    state: directory

- name: Ensure CouchPotato dependencies are installed
  package: name={{ couchpotato_dependencies }} state=present

- name: Fetch CouchPotato source code
  git:
    repo: "{{ couchpotato_clone_uri }}"
    dest: "{{ couchpotato_user_home }}/src"
    update: false
    accept_hostkey: true
  become: true
  become_user: "{{ couchpotato_user_name }}"

- name: Deploy CouchPotato service manifest
  template:
    src: "{{ couchpotato_service_file.src }}"
    dest: "{{ couchpotato_service_file.dest }}"
    owner: root
    group: root
    mode: 0664
  notify:
    - Restart CouchPotato service

- meta: flush_handlers

- name: Ensure the CouchPotato service is running and enabled on boot
  service: name=couchpotato state=started enabled=yes
